"""empty message

Revision ID: 4a1bbf70d1a5
Revises: f8b4e2b5ace4
Create Date: 2018-12-24 03:01:37.103415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1bbf70d1a5'
down_revision = 'f8b4e2b5ace4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'purchase_item', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_item', 'purchase', ['purchase_id'], ['id'])
    op.drop_column('purchase_item', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'purchase_item', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_item', 'purchase', ['order_id'], ['id'])
    op.drop_column('purchase_item', 'purchase_id')
    # ### end Alembic commands ###
